apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-lab-pre
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JI1047/jupjup.git
    targetRevision: main
    path: gitops/rollout-lab/overlays/pre-improvement
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
